language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  nosetests -w test/unittests --with-coverage --cover-package=sumatra
